blank_issues_enabled: false
contact_links:
  - name: QBCore Discord Server
    url: https://discord.gg/qbcore
    about: Ask questions, receive support, and discuss with the community in our Discord server.
