QBShared = QBShared or {}
QBShared.Weapons = {
	-- // WEAPONS
	--Customs
	[`VEHICLE_WEAPON_TURRET_BCAT`] 	 = {['name'] = 'VEHICLE_WEAPON_TURRET_BCAT',	['label'] = 'TARV', 						['ammotype'] = nil, 						['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_shovel`] 				 = {['name'] = 'weapon_shovel',             	['label'] = 'Pelle', 						['ammotype'] = nil, 						['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_pickaxe`] 				 = {['name'] = 'weapon_pickaxe', 	        	['label'] = 'Pioche', 						['ammotype'] = nil, 						['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_beanbag`] 				 = {['name'] = 'weapon_beanbag', 		 		['label'] = 'Beanbag', 						['ammotype'] = 'AMMO_SHOTGUN', 				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`WEAPON_COMBATRIFLE`] 			 = {['name'] = 'weapon_combatrifle', 			['label'] = 'Fusil de Combat', 				['ammotype'] = "AMMO_RIFLE", 				['damagereason'] = 'Ended / Rifled / Shot down / Floored'},

	-- Melee
	[`weapon_unarmed`] 				 = {['name'] = 'weapon_unarmed', 				['label'] = 'Poings', 						['ammotype'] = nil, 						['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_dagger`] 				 = {['name'] = 'weapon_dagger', 				['label'] = 'Dague', 						['ammotype'] = nil,							['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_bat`] 					 = {['name'] = 'weapon_bat', 					['label'] = 'Batte', 						['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_bottle`] 				 = {['name'] = 'weapon_bottle', 				['label'] = 'Cul de Bouteille', 			['ammotype'] = nil,							['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_crowbar`] 				 = {['name'] = 'weapon_crowbar', 				['label'] = 'Pied de biche', 				['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_flashlight`] 			 = {['name'] = 'weapon_flashlight', 			['label'] = 'Lampe Torche', 				['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_golfclub`] 			 = {['name'] = 'weapon_golfclub', 				['label'] = 'Club de golf', 				['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_hammer`] 				 = {['name'] = 'weapon_hammer', 				['label'] = 'Marteau', 						['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_hatchet`] 				 = {['name'] = 'weapon_hatchet', 				['label'] = 'Hache', 						['ammotype'] = nil,							['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_knuckle`] 				 = {['name'] = 'weapon_knuckle', 				['label'] = 'Poing Américain', 				['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_knife`] 				 = {['name'] = 'weapon_knife', 					['label'] = 'Couteau', 						['ammotype'] = nil,							['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_machete`] 				 = {['name'] = 'weapon_machete', 				['label'] = 'Machette', 					['ammotype'] = nil,							['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_switchblade`] 			 = {['name'] = 'weapon_switchblade', 			['label'] = 'Cran d\'arrêt', 				['ammotype'] = nil,							['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_nightstick`] 			 = {['name'] = 'weapon_nightstick', 			['label'] = 'Matraque', 					['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_wrench`] 				 = {['name'] = 'weapon_wrench', 				['label'] = 'Clé anglaise', 				['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_battleaxe`] 			 = {['name'] = 'weapon_battleaxe', 				['label'] = 'Hache de guerre', 				['ammotype'] = nil,							['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_poolcue`] 				 = {['name'] = 'weapon_poolcue', 				['label'] = 'Queue de billard', 			['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_briefcase`] 			 = {['name'] = 'weapon_briefcase', 				['label'] = 'Malette', 						['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_briefcase_02`] 		 = {['name'] = 'weapon_briefcase_02', 	    	['label'] = 'Malette', 						['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_garbagebag`] 			 = {['name'] = 'weapon_garbagebag', 			['label'] = 'Sac Poubelle', 				['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_handcuffs`] 			 = {['name'] = 'weapon_handcuffs', 				['label'] = 'Menottes', 					['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_bread`] 				 = {['name'] = 'weapon_bread', 					['label'] = 'Baguette', 					['ammotype'] = nil,							['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_stone_hatchet`] 		 = {['name'] = 'weapon_stone_hatchet', 	    	['label'] = 'Hachette en pierre', 			['ammotype'] = nil,							['damagereason'] = 'Knifed / Stabbed / Eviscerated'},

    -- Handguns
	[`weapon_pistol`] 				 = {['name'] = 'weapon_pistol', 				['label'] = 'Berretta', 					['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_pistol_mk2`] 			 = {['name'] = 'weapon_pistol_mk2', 			['label'] = 'Berretta Amélioré', 			['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_combatpistol`] 		 = {['name'] = 'weapon_combatpistol', 			['label'] = 'Glock 17', 					['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_appistol`] 			 = {['name'] = 'weapon_appistol', 				['label'] = 'Glock 19', 					['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_stungun`] 				 = {['name'] = 'weapon_stungun', 				['label'] = 'Tazer', 						['ammotype'] = 'AMMO_STUNGUN',				['damagereason'] = 'Died'},
	[`weapon_pistol50`] 			 = {['name'] = 'weapon_pistol50', 				['label'] = 'Calibre .50', 					['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_snspistol`] 			 = {['name'] = 'weapon_snspistol', 				['label'] = 'Pétoire', 						['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_snspistol_mk2`] 	     = {['name'] = 'weapon_snspistol_mk2', 			['label'] = 'Pétoire MK2', 					['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_heavypistol`] 			 = {['name'] = 'weapon_heavypistol', 			['label'] = 'Pistolet lourd', 				['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_vintagepistol`] 		 = {['name'] = 'weapon_vintagepistol', 			['label'] = 'Pistolet vintage', 			['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_flaregun`] 			 = {['name'] = 'weapon_flaregun', 				['label'] = 'Pistolet de détresse', 		['ammotype'] = 'AMMO_FLARE',				['damagereason'] = 'Died'},
	[`weapon_marksmanpistol`] 		 = {['name'] = 'weapon_marksmanpistol', 		['label'] = 'Marksman Pistol', 				['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_revolver`] 			 = {['name'] = 'weapon_revolver', 				['label'] = 'Revolver', 					['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_revolver_mk2`] 		 = {['name'] = 'weapon_revolver_mk2', 			['label'] = 'Violence', 					['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_doubleaction`] 	     = {['name'] = 'weapon_doubleaction', 			['label'] = 'Revolver Double Action',		['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_raypistol`]			 = {['name'] = 'weapon_raypistol',				['label'] = 'Weapon Raypistol',				['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_ceramicpistol`]		 = {['name'] = 'weapon_ceramicpistol', 			['label'] = 'Pistolet Céramique',			['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_navyrevolver`]        	 = {['name'] = 'weapon_navyrevolver', 			['label'] = 'Revolver Céramique',			['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_gadgetpistol`] 		 = {['name'] = 'weapon_gadgetpistol', 			['label'] = 'Pistolet gadget',				['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_stungun_mp`] 			 = {['name'] = 'weapon_stungun_mp', 			['label'] = 'Tazer', 						['ammotype'] = 'AMMO_STUNGUN',				['damagereason'] = 'Died'},

    -- Submachine Guns
	[`weapon_microsmg`] 			 = {['name'] = 'weapon_microsmg', 				['label'] = 'Micro SMG', 					['ammotype'] = 'AMMO_SMG',					['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_smg`] 				 	 = {['name'] = 'weapon_smg', 					['label'] = 'SMG', 							['ammotype'] = 'AMMO_SMG',					['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_smg_mk2`] 				 = {['name'] = 'weapon_smg_mk2', 				['label'] = 'PD MP5 2', 					['ammotype'] = 'AMMO_SMG',					['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_assaultsmg`] 			 = {['name'] = 'weapon_assaultsmg', 			['label'] = 'Assault SMG', 					['ammotype'] = 'AMMO_SMG',					['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_combatpdw`] 			 = {['name'] = 'weapon_combatpdw', 				['label'] = 'Combat PDW', 					['ammotype'] = 'AMMO_SMG',					['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_machinepistol`] 		 = {['name'] = 'weapon_machinepistol', 			['label'] = 'Tec-9', 						['ammotype'] = 'AMMO_PISTOL',				['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_minismg`] 				 = {['name'] = 'weapon_minismg', 				['label'] = 'Mini SMG', 					['ammotype'] = 'AMMO_SMG',					['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_raycarbine`]	         = {['name'] = 'weapon_raycarbine', 			['label'] = 'Weapon Raycarbine',			['ammotype'] = 'AMMO_SMG',					['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},

    -- Shotguns
	[`weapon_pumpshotgun`] 			 = {['name'] = 'weapon_pumpshotgun', 	 		['label'] = 'Fusil a pompe', 				['ammotype'] = 'AMMO_SHOTGUN',				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_pumpshotgun_mk2`]		 = {['name'] = 'weapon_pumpshotgun_mk2',		['label'] = 'Fusil a pompe Mk2', 			['ammotype'] = 'AMMO_SHOTGUN',				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_sawnoffshotgun`] 		 = {['name'] = 'weapon_sawnoffshotgun', 		['label'] = 'Fusil a canon scié', 			['ammotype'] = 'AMMO_SHOTGUN',				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_assaultshotgun`] 		 = {['name'] = 'weapon_assaultshotgun', 		['label'] = 'Fusil d\'assaut', 				['ammotype'] = 'AMMO_SHOTGUN',				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_bullpupshotgun`] 		 = {['name'] = 'weapon_bullpupshotgun', 		['label'] = 'Bullpup Shotgun', 				['ammotype'] = 'AMMO_SHOTGUN',				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_musket`] 			     = {['name'] = 'weapon_musket', 				['label'] = 'Mousquet', 					['ammotype'] = 'AMMO_SHOTGUN',				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_heavyshotgun`] 		 = {['name'] = 'weapon_heavyshotgun', 	 		['label'] = 'Fusil a Pompe Lourd', 			['ammotype'] = 'AMMO_SHOTGUN',				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_dbshotgun`] 			 = {['name'] = 'weapon_dbshotgun', 		 		['label'] = 'Double-barrel Shotgun', 		['ammotype'] = 'AMMO_SHOTGUN',				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_autoshotgun`] 			 = {['name'] = 'weapon_autoshotgun', 	 		['label'] = 'Fusil a Pompe Automatique', 	['ammotype'] = 'AMMO_SHOTGUN',				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_combatshotgun`]		 = {['name'] = 'weapon_combatshotgun', 			['label'] = 'Fusil a Pompe de Combat',		['ammotype'] = 'AMMO_SHOTGUN',				['damagereason'] = 'Devastated / Pulverized / Shotgunned'},

    -- Assault Rifles
	[`weapon_assaultrifle`] 		 = {['name'] = 'weapon_assaultrifle', 	 		['label'] = 'AK-47',		 				['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_assaultrifle_mk2`] 	 = {['name'] = 'weapon_assaultrifle_mk2', 		['label'] = 'AK-47 MK2', 					['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_carbinerifle`] 		 = {['name'] = 'weapon_carbinerifle', 	 		['label'] = 'AR-15', 						['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_carbinerifle_mk2`] 	 = {['name'] = 'weapon_carbinerifle_mk2', 		['label'] = 'PD 762', 						['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_advancedrifle`] 		 = {['name'] = 'weapon_advancedrifle', 	 		['label'] = 'Fusil avancé', 				['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_specialcarbine`] 		 = {['name'] = 'weapon_specialcarbine', 		['label'] = 'G-36C', 						['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_specialcarbine_mk2`]	 = {['name'] = 'weapon_specialcarbine_mk2',		['label'] = 'G-36K',						['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_bullpuprifle`] 		 = {['name'] = 'weapon_bullpuprifle', 	 		['label'] = 'Fusil Bullbup', 				['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_bullpuprifle_mk2`]		 = {['name'] = 'weapon_bullpuprifle_mk2', 		['label'] = 'Fusil Bullbup MK2',			['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_compactrifle`] 		 = {['name'] = 'weapon_compactrifle', 	 		['label'] = 'Fusil compact', 				['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_militaryrifle`]		 = {['name'] = 'weapon_militaryrifle', 			['label'] = 'Aug A3',						['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_heavyrifle`] 			 = {['name'] = 'weapon_heavyrifle', 	 		['label'] = 'Scar-H', 						['ammotype'] = 'AMMO_RIFLE',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},

    -- Light Machine Guns
	[`weapon_mg`] 					 = {['name'] = 'weapon_mg', 					['label'] = 'Machinegun', 					['ammotype'] = 'AMMO_MG',				['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[`weapon_combatmg`] 			 = {['name'] = 'weapon_combatmg', 				['label'] = 'Combat MG', 					['ammotype'] = 'AMMO_MG',				['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[`weapon_combatmg_mk2`]	 		 = {['name'] = 'weapon_combatmg_mk2', 			['label'] = 'Weapon Combatmg MK2',			['ammotype'] = 'AMMO_MG',				['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[`weapon_gusenberg`] 			 = {['name'] = 'weapon_gusenberg', 				['label'] = 'Thompson SMG', 				['ammotype'] = 'AMMO_MG',				['damagereason'] = 'Machine gunned / Sprayed / Ruined'},

    -- Sniper Rifles
	[`weapon_sniperrifle`] 			 = {['name'] = 'weapon_sniperrifle', 	 		['label'] = 'Sniper', 						['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_heavysniper`] 			 = {['name'] = 'weapon_heavysniper', 	 		['label'] = 'Sniper lourd', 				['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_heavysniper_mk2`]		 = {['name'] = 'weapon_heavysniper_mk2', 		['label'] = 'Sniper lourd MK2',				['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_marksmanrifle`] 		 = {['name'] = 'weapon_marksmanrifle', 	 		['label'] = 'Marksman Rifle', 				['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_marksmanrifle_mk2`]	 = {['name'] = 'weapon_marksmanrifle_mk2',		['label'] = 'Weapon Marksmanrifle MK2',		['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_remotesniper`] 		 = {['name'] = 'weapon_remotesniper', 	 		['label'] = 'Remote Sniper', 				['ammotype'] = 'AMMO_SNIPER_REMOTE',	['damagereason'] = 'Sniped / Picked off / Scoped'},

    -- Heavy Weapons
	[`weapon_rpg`] 					 = {['name'] = 'weapon_rpg', 			      	['label'] = 'RPG', 							['ammotype'] = 'AMMO_RPG',				['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_grenadelauncher`] 		 = {['name'] = 'weapon_grenadelauncher', 	  	['label'] = 'Lance Grenade', 				['ammotype'] = 'AMMO_GRENADELAUNCHER',	['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_grenadelauncher_smoke`] = {['name'] = 'weapon_grenadelauncher_smoke',	['label'] = 'Lance Grenade Fumigène',		['ammotype'] = 'AMMO_GRENADELAUNCHER',	['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_minigun`] 				 = {['name'] = 'weapon_minigun', 		      	['label'] = 'Mini-gun', 					['ammotype'] = 'AMMO_MINIGUN',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_firework`] 			 = {['name'] = 'weapon_firework', 		 	  	['label'] = 'Lance Feu D\'artifice', 		['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_railgun`] 				 = {['name'] = 'weapon_railgun', 		 	  	['label'] = 'Railgun', 						['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_hominglauncher`] 		 = {['name'] = 'weapon_hominglauncher', 	 	['label'] = 'Lance Missile', 				['ammotype'] = 'AMMO_STINGER',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_compactlauncher`] 		 = {['name'] = 'weapon_compactlauncher',  	  	['label'] = 'Lanceur compact', 				['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_rayminigun`]			 = {['name'] = 'weapon_rayminigun', 		 	['label'] = 'Weapon Rayminigun',			['ammotype'] = 'AMMO_MINIGUN',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
    [`weapon_emplauncher`] 			 = {['name'] = 'weapon_emplauncher', 			['label'] = 'EMP Launcher', 				['ammotype'] = 'AMMO_EMPLAUNCHER',		['damagereason'] = 'Died'},

    -- Throwables
	[`weapon_grenade`] 				 = {['name'] = 'weapon_grenade', 				['label'] = 'Grenade', 						['ammotype'] = nil,						['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_bzgas`] 				 = {['name'] = 'weapon_bzgas', 					['label'] = 'BZ Gas', 						['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_molotov`] 				 = {['name'] = 'weapon_molotov', 				['label'] = 'Molotov', 						['ammotype'] = nil,						['damagereason'] = 'Torched / Flambeed / Barbecued'},
	[`weapon_stickybomb`] 			 = {['name'] = 'weapon_stickybomb', 			['label'] = 'C4', 							['ammotype'] = nil,						['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_proxmine`] 			 = {['name'] = 'weapon_proxmine', 				['label'] = 'Mine de proximité', 			['ammotype'] = nil,						['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_snowball`] 			 = {['name'] = 'weapon_snowball', 				['label'] = 'Boule de neige', 				['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_pipebomb`] 			 = {['name'] = 'weapon_pipebomb', 				['label'] = 'Bomb artisanale', 				['ammotype'] = nil,						['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_ball`] 				 = {['name'] = 'weapon_ball', 					['label'] = 'Balle', 						['ammotype'] = 'AMMO_BALL',				['damagereason'] = 'Died'},
	[`weapon_smokegrenade`] 		 = {['name'] = 'weapon_smokegrenade', 			['label'] = 'Grenade Fumigène', 			['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_flare`] 				 = {['name'] = 'weapon_flare', 					['label'] = 'Pistolet de détresse', 		['ammotype'] = 'AMMO_FLARE',			['damagereason'] = 'Died'},
  
	-- Miscellaneous
	[`weapon_petrolcan`] 			= {['name'] = 'weapon_petrolcan', 		 		['label'] = 'Bidon Essence', 				['ammotype'] = 'AMMO_PETROLCAN',		['damagereason'] = 'Died'},
	[`gadget_parachute`] 			= {['name'] = 'gadget_parachute', 		 		['label'] = 'Parachute', 					['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_fireextinguisher`] 	= {['name'] = 'weapon_fireextinguisher',		['label'] = 'Extincteur',					['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_hazardcan`]			= {['name'] = 'weapon_hazardcan',				['label'] = 'Jerry Can Radioactif',			['ammotype'] = 'AMMO_PETROLCAN',		['damagereason'] = 'Died'},
    [`weapon_fertilizercan`]		= {['name'] = 'weapon_fertilizercan',			['label'] = 'Fertilizer Can',				['ammotype'] = 'AMMO_FERTILIZERCAN',	['damagereason'] = 'Died'},
	[`weapon_barbed_wire`]			= {['name'] = 'weapon_barbed_wire',				['label'] = 'Fil barbelé',					['ammotype'] = nil,						['damagereason'] = 'Prodded'},
	[`weapon_drowning`]				= {['name'] = 'weapon_drowning',				['label'] = 'Noyé',							['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_drowning_in_vehicle`]	= {['name'] = 'weapon_drowning_in_vehicle',		['label'] = 'Noyé dans un véhicule',		['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_bleeding`]				= {['name'] = 'weapon_bleeding',				['label'] = 'Saigne',						['ammotype'] = nil,						['damagereason'] = 'Bled out'},
	[`weapon_electric_fence`]		= {['name'] = 'weapon_electric_fence',			['label'] = 'Barrière électrique',			['ammotype'] = nil,						['damagereason'] = 'Fried'},
	[`weapon_explosion`]			= {['name'] = 'weapon_explosion',				['label'] = 'Explosion',					['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_fall`]					= {['name'] = 'weapon_fall',					['label'] = 'Chute',						['ammotype'] = nil,						['damagereason'] = 'Committed suicide'},
	[`weapon_exhaustion`]			= {['name'] = 'weapon_exhaustion',				['label'] = 'Fatigue',						['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_hit_by_water_cannon`]	= {['name'] = 'weapon_hit_by_water_cannon',		['label'] = 'Canon à eau',					['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_rammed_by_car`]		= {['name'] = 'weapon_rammed_by_car',			['label'] = 'Foncé dedans - Vehicule',		['ammotype'] = nil,						['damagereason'] = 'Flattened / Ran over / Ran down'},
	[`weapon_run_over_by_car`]		= {['name'] = 'weapon_run_over_by_car',			['label'] = 'écrasé - Vehicule',			['ammotype'] = nil,						['damagereason'] = 'Flattened / Ran over / Ran down'},
	[`weapon_heli_crash`]			= {['name'] = 'weapon_heli_crash',				['label'] = 'Heli Crash',					['ammotype'] = nil,						['damagereason'] = 'Helicopter Crash'},
	[`weapon_fire`]					= {['name'] = 'weapon_fire',					['label'] = 'Feu',							['ammotype'] = nil,						['damagereason'] = 'Torched / Flambeed / Barbecued'},

	-- Animals
	[`weapon_animal`]				= {['name'] = 'weapon_animal',					['label'] = 'Animal',						['ammotype'] = nil,						['damagereason'] = 'Mauled'},
    [`weapon_cougar`]				= {['name'] = 'weapon_cougar',					['label'] = 'Cougar',						['ammotype'] = nil,						['damagereason'] = 'Mauled'},
} 