local themes = Config.theme.themes
-- TODO: Do we need to store this path somewhere central so it can be used in other resources?
local filePath = GetResourcePath('qb-core') .. "/html/css/themes.css"
local element = Config.theme.element

function generateTheme()
    print('Removing existing Theme file' .. filePath)
    os.remove(filePath)

    local cssFile = io.open(filePath, "a")
    cssFile:write('/* DO NOT MANUALLY EDIT THIS FILE. This file is generated by QBCore. Adjust config.lua*/\n')

    for themeName in pairs(themes) do
        print('Adding theme ' .. themeName .. ' to file')
        cssFile:write(element .. "[theme=" .. string.lower(themeName) .. "] {")

        for property, value in pairs(themes[themeName]) do
            print ('Adding property ' .. property .. ' with value ' .. value .. ' to file')
            cssFile:write("--" .. string.lower(property) .. ": " .. string.lower(value) .. ";")
        end

        cssFile:write('}\n')
    end

    cssFile:close()
    print('Theme file generated - ' .. filePath)
end

RegisterCommand('generateTheme', function()
    -- TODO: themes.lua config should be re-loaded but currently this does not work
    return generateTheme()
end, false)

AddEventHandler('onResourceStart', function(resourceName)
    if (GetCurrentResourceName() ~= resourceName) then
        return
    end
    generateTheme()
end)

