QBShared = QBShared or {}
local Items = {

    -- WEAPONS
    -- Melee
    weapon_unarmed               = { label = 'Fists', weight = 1000, type = 'weapon', image = 'placeholder.png', unique = true, description = 'Fisticuffs' },
    weapon_dagger                = { label = 'Dagger', weight = 1000, type = 'weapon', unique = true, description = 'A short knife with a pointed and edged blade, used as a weapon' },
    weapon_bat                   = { label = 'Bat', weight = 1000, type = 'weapon', unique = true, description = 'Used for hitting a ball in sports (or other things)' },
    weapon_bottle                = { label = 'Broken Bottle', weight = 1000, type = 'weapon', unique = true, description = 'A broken bottle' },
    weapon_crowbar               = { label = 'Crowbar', weight = 1000, type = 'weapon', unique = true, description = 'An iron bar with a flattened end, used as a lever' },
    weapon_flashlight            = { label = 'Flashlight', weight = 1000, type = 'weapon', unique = true, description = 'A battery-operated portable light' },
    weapon_golfclub              = { label = 'Golfclub', weight = 1000, type = 'weapon', unique = true, description = 'A club used to hit the ball in golf' },
    weapon_hammer                = { label = 'Hammer', weight = 1000, type = 'weapon', unique = true, description = 'Used for jobs such as breaking things (legs) and driving in nails' },
    weapon_hatchet               = { label = 'Hatchet', weight = 1000, type = 'weapon', unique = true, description = 'A small axe with a short handle for use in one hand' },
    weapon_knuckle               = { label = 'Knuckle', weight = 1000, type = 'weapon', unique = true, description = 'A metal guard worn over the knuckles in fighting, especially to increase the effect of the blows' },
    weapon_knife                 = { label = 'Knife', weight = 1000, type = 'weapon', unique = true, description = 'An instrument composed of a blade fixed into a handle, used for cutting or as a weapon' },
    weapon_machete               = { label = 'Machete', weight = 1000, type = 'weapon', unique = true, description = 'A broad, heavy knife used as a weapon' },
    weapon_switchblade           = { label = 'Switchblade', weight = 1000, type = 'weapon', unique = true, description = 'A knife with a blade that springs out from the handle when a button is pressed' },
    weapon_nightstick            = { label = 'Nightstick', weight = 1000, type = 'weapon', unique = true, description = 'A police officer\'s club or billy' },
    weapon_wrench                = { label = 'Wrench', weight = 1000, type = 'weapon', unique = true, description = 'A tool used for gripping and turning nuts, bolts, pipes, etc' },
    weapon_battleaxe             = { label = 'Battle Axe', weight = 1000, type = 'weapon', unique = true, description = 'A large broad-bladed axe used in ancient warfare' },
    weapon_poolcue               = { label = 'Poolcue', weight = 1000, type = 'weapon', unique = true, description = 'A stick used to strike a ball, usually the cue ball (or other things)' },
    weapon_briefcase             = { label = 'Briefcase', weight = 1000, type = 'weapon', unique = true, description = 'A briefcase for storing important documents' },
    weapon_briefcase_02          = { label = 'Suitcase', weight = 1000, type = 'weapon', image = 'weapon_briefcase2.png', unique = true, description = 'Wonderfull for nice vacation to Liberty City' },
    weapon_garbagebag            = { label = 'Garbage Bag', weight = 1000, type = 'weapon', unique = true, description = 'A garbage bag' },
    weapon_handcuffs             = { label = 'Handcuffs', weight = 1000, type = 'weapon', unique = true, description = 'A pair of lockable linked metal rings for securing a prisoner\'s wrists' },
    weapon_bread                 = { label = 'Baquette', weight = 1000, type = 'weapon', image = 'baquette.png', unique = true, description = 'Bread...?' },
    weapon_stone_hatchet         = { label = 'Stone Hatchet', weight = 1000, type = 'weapon', unique = true, useable = true, description = 'Stone Hatchet' },
    weapon_candycane             = { label = 'Candy Cane', weight = 1000, type = 'weapon', image = 'weapon_candycane', unique = true, useable = true, description = 'Candy Cane' },

    -- Handguns
    weapon_pistol                = { label = 'Walther P99', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'A small firearm designed to be held in one hand' },
    weapon_pistol_mk2            = { label = 'Pistol Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'An upgraded small firearm designed to be held in one hand' },
    weapon_combatpistol          = { label = 'Combat Pistol', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'A combat version small firearm designed to be held in one hand' },
    weapon_appistol              = { label = 'AP Pistol', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'A small firearm designed to be held in one hand that is automatic' },
    weapon_stungun               = { label = 'Taser', weight = 1000, type = 'weapon', unique = true, description = 'A weapon firing barbs attached by wires to batteries, causing temporary paralysis' },
    weapon_pistol50              = { label = 'Pistol .50', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'A .50 caliber firearm designed to be held with both hands' },
    weapon_snspistol             = { label = 'SNS Pistol', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'A very small firearm designed to be easily concealed' },
    weapon_heavypistol           = { label = 'Heavy Pistol', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'A hefty firearm designed to be held in one hand (or attempted)' },
    weapon_vintagepistol         = { label = 'Vintage Pistol', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'An antique firearm designed to be held in one hand' },
    weapon_flaregun              = { label = 'Flare Gun', weight = 1000, type = 'weapon', ammotype = 'AMMO_FLARE', unique = true, description = 'A handgun for firing signal rockets' },
    weapon_marksmanpistol        = { label = 'Marksman Pistol', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'A very accurate small firearm designed to be held in one hand' },
    weapon_revolver              = { label = 'Revolver', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'A pistol with revolving chambers enabling several shots to be fired without reloading' },
    weapon_revolver_mk2          = { label = 'Violence', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, useable = true, description = 'da Violence' },
    weapon_doubleaction          = { label = 'Double Action Revolver', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, useable = true, description = 'Double Action Revolver' },
    weapon_snspistol_mk2         = { label = 'SNS Pistol Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, useable = true, description = 'SNS Pistol MK2' },
    weapon_raypistol             = { label = 'Up-n-Atomizer', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, useable = true, description = 'Weapon Raypistol' },
    weapon_ceramicpistol         = { label = 'Ceramic Pistol', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, useable = true, description = 'Weapon Ceramicpistol' },
    weapon_navyrevolver          = { label = 'Navy Revolver', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, useable = true, description = 'Weapon Navyrevolver' },
    weapon_gadgetpistol          = { label = 'Perico Pistol', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, useable = true, description = 'Weapon Gadgetpistol' },
    weapon_pistolxm3             = { label = 'Pistol XM3', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, useable = true, description = 'Pistol XM3' },

    -- Submachine Guns
    weapon_microsmg              = { label = 'Micro SMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', unique = true, description = 'A handheld light                                                                                                                                                                                                                                                                                                                                                            weight machine gun' },
    weapon_smg                   = { label = 'SMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', unique = true, description = 'A handheld light                                                                                                                                                                                                                                                                                                                                                                 weight machine gun' },
    weapon_smg_mk2               = { label = 'SMG Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', unique = true, useable = true, description = 'SMG MK2' },
    weapon_assaultsmg            = { label = 'Assault SMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', unique = true, description = 'An assault version of a handheld light                                                                                                                                                                                                                                                                                                                                    weight machine gun' },
    weapon_combatpdw             = { label = 'Combat PDW', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', unique = true, description = 'A combat version of a handheld light                                                                                                                                                                                                                                                                                                                                       weight machine gun' },
    weapon_machinepistol         = { label = 'Tec-9', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', unique = true, description = 'A self-loading pistol capable of burst or fully automatic fire' },
    weapon_minismg               = { label = 'Mini SMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', unique = true, description = 'A mini handheld light                                                                                                                                                                                                                                                                                                                                                        weight machine gun' },
    weapon_raycarbine            = { label = 'Unholy Hellbringer', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', unique = true, useable = true, description = 'Weapon Raycarbine' },

    -- Shotguns
    weapon_pumpshotgun           = { label = 'Pump Shotgun', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', unique = true, description = 'A pump-action smoothbore gun for firing small shot at short range' },
    weapon_sawnoffshotgun        = { label = 'Sawn-off Shotgun', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', unique = true, description = 'A sawn-off smoothbore gun for firing small shot at short range' },
    weapon_assaultshotgun        = { label = 'Assault Shotgun', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', unique = true, description = 'An assault version of asmoothbore gun for firing small shot at short range' },
    weapon_bullpupshotgun        = { label = 'Bullpup Shotgun', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', unique = true, description = 'A compact smoothbore gun for firing small shot at short range' },
    weapon_musket                = { label = 'Musket', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', unique = true, description = 'An infantryman\'s light gun with a long barrel, typically smooth-bored, muzzleloading, and fired from the shoulder' },
    weapon_heavyshotgun          = { label = 'Heavy Shotgun', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', unique = true, description = 'A large smoothbore gun for firing small shot at short range' },
    weapon_dbshotgun             = { label = 'Double-barrel Shotgun', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', unique = true, description = 'A shotgun with two parallel barrels, allowing two single shots to be fired in quick succession' },
    weapon_autoshotgun           = { label = 'Auto Shotgun', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', unique = true, description = 'A shotgun capable of rapid continous fire' },
    weapon_pumpshotgun_mk2       = { label = 'Pumpshotgun Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', unique = true, useable = true, description = 'Pumpshotgun MK2' },
    weapon_combatshotgun         = { label = 'Combat Shotgun', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', unique = true, useable = true, description = 'Weapon Combatshotgun' },

    -- Assault Rifles
    weapon_assaultrifle          = { label = 'Assault Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, description = 'A rapid-fire, magazine-fed automatic rifle designed for infantry use' },
    weapon_assaultrifle_mk2      = { label = 'Assault Rifle Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, useable = true, description = 'Assault Rifle MK2' },
    weapon_carbinerifle          = { label = 'Carbine Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, description = 'A light                                                                                                                                                                                                                                                                                                                                                               weight automatic rifle' },
    weapon_carbinerifle_mk2      = { label = 'Carbine Rifle Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, useable = true, description = 'Carbine Rifle MK2' },
    weapon_advancedrifle         = { label = 'Advanced Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, description = 'An assault version of a rapid-fire, magazine-fed automatic rifle designed for infantry use' },
    weapon_specialcarbine        = { label = 'Special Carbine', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, description = 'An extremely versatile assault rifle for any combat situation' },
    weapon_bullpuprifle          = { label = 'Bullpup Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, description = 'A compact automatic assault rifle' },
    weapon_compactrifle          = { label = 'Compact Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, description = 'A compact version of an assault rifle' },
    weapon_specialcarbine_mk2    = { label = 'Special Carbine Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, useable = true, description = 'Weapon Wpecialcarbine MK2' },
    weapon_bullpuprifle_mk2      = { label = 'Bullpup Rifle Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, useable = true, description = 'Bull Puprifle MK2' },
    weapon_militaryrifle         = { label = 'Military Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', unique = true, useable = true, description = 'Weapon Militaryrifle' },

    -- Light Machine Guns
    weapon_mg                    = { label = 'Machinegun', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', unique = true, description = 'An automatic gun that fires bullets in rapid succession for as long as the trigger is pressed' },
    weapon_combatmg              = { label = 'Combat MG', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', unique = true, description = 'A combat version of an automatic gun that fires bullets in rapid succession for as long as the trigger is pressed' },
    weapon_gusenberg             = { label = 'Thompson SMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', unique = true, description = 'An automatic rifle commonly referred to as a tommy gun' },
    weapon_combatmg_mk2          = { label = 'Combat MG Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', unique = true, useable = true, description = 'Weapon Combatmg MK2' },

    -- Sniper Rifles
    weapon_sniperrifle           = { label = 'Sniper Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', unique = true, description = 'A high-precision, long-range rifle' },
    weapon_heavysniper           = { label = 'Heavy Sniper', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', unique = true, description = 'An upgraded high-precision, long-range rifle' },
    weapon_marksmanrifle         = { label = 'Marksman Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', unique = true, description = 'A very accurate single-fire rifle' },
    weapon_remotesniper          = { label = 'Remote Sniper', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER_REMOTE', unique = true, description = 'A portable high-precision, long-range rifle' },
    weapon_heavysniper_mk2       = { label = 'Heavy Sniper Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', unique = true, useable = true, description = 'Weapon Heavysniper MK2' },
    weapon_marksmanrifle_mk2     = { label = 'Marksman Rifle Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', unique = true, useable = true, description = 'Weapon Marksmanrifle MK2' },

    -- Heavy Weapons
    weapon_rpg                   = { label = 'RPG', weight = 1000, type = 'weapon', ammotype = 'AMMO_RPG', unique = true, description = 'A rocket-propelled grenade launcher' },
    weapon_grenadelauncher       = { label = 'Grenade Launcher', weight = 1000, type = 'weapon', ammotype = 'AMMO_GRENADELAUNCHER', unique = true, description = 'A weapon that fires a specially-designed large-caliber projectile, often with an explosive, smoke or gas warhead' },
    weapon_grenadelauncher_smoke = { label = 'Smoke Grenade Launcher', weight = 1000, type = 'weapon', ammotype = 'AMMO_GRENADELAUNCHER', image = 'weapon_smokegrenade.png', unique = true, description = 'A bomb that produces a lot of smoke when it explodes' },
    weapon_minigun               = { label = 'Minigun', weight = 1000, type = 'weapon', ammotype = 'AMMO_MINIGUN', unique = true, description = 'A portable machine gun consisting of a rotating cluster of six barrels and capable of variable rates of fire of up to 6,000 rounds per minute' },
    weapon_firework              = { label = 'Firework Launcher', weight = 1000, type = 'weapon', unique = true, description = 'A device containing gunpowder and other combustible chemicals that causes a spectacular explosion when ignited' },
    weapon_railgun               = { label = 'Railgun', weight = 1000, type = 'weapon', unique = true, description = 'A weapon that uses electromagnetic force to launch high velocity projectiles' },
    weapon_railgunxm3            = { label = 'Railgun XM3', weight = 1000, type = 'weapon', unique = true, description = 'A weapon that uses electromagnetic force to launch high velocity projectiles' },
    weapon_hominglauncher        = { label = 'Homing Launcher', weight = 1000, type = 'weapon', ammotype = 'AMMO_STINGER', unique = true, description = 'A weapon fitted with an electronic device that enables it to find and hit a target' },
    weapon_compactlauncher       = { label = 'Compact Launcher', weight = 1000, type = 'weapon', unique = true, description = 'A compact grenade launcher' },
    weapon_rayminigun            = { label = 'Widowmaker', weight = 1000, type = 'weapon', ammotype = 'AMMO_MINIGUN', unique = true, useable = true, description = 'Weapon Rayminigun' },

    -- Throwables
    weapon_grenade               = { label = 'Grenade', weight = 1000, type = 'weapon', unique = true, description = 'A handheld throwable bomb' },
    weapon_bzgas                 = { label = 'BZ Gas', weight = 1000, type = 'weapon', unique = true, description = 'A cannister of gas that causes extreme pain' },
    weapon_molotov               = { label = 'Molotov', weight = 1000, type = 'weapon', unique = true, description = 'A crude bomb made of a bottle filled with a flammable liquid and fitted with a wick for lighting' },
    weapon_stickybomb            = { label = 'C4', weight = 1000, type = 'weapon', unique = true, description = 'An explosive charge covered with an adhesive that when thrown against an object sticks until it explodes' },
    weapon_proxmine              = { label = 'Proxmine Grenade', weight = 1000, type = 'weapon', image = 'weapon_proximitymine.png', unique = true, description = 'A bomb placed on the ground that detonates when going within its proximity' },
    weapon_snowball              = { label = 'Snowball', weight = 1000, type = 'weapon', unique = true, description = 'A ball of packed snow, especially one made for throwing at other people for fun' },
    weapon_pipebomb              = { label = 'Pipe Bomb', weight = 1000, type = 'weapon', unique = true, description = 'A homemade bomb, the components of which are contained in a pipe' },
    weapon_ball                  = { label = 'Ball', weight = 1000, type = 'weapon', ammotype = 'AMMO_BALL', unique = true, description = 'A solid or hollow spherical or egg-shaped object that is kicked, thrown, or hit in a game' },
    weapon_smokegrenade          = { label = 'Smoke Grenade', weight = 1000, type = 'weapon', image = 'weapon_c4.png', unique = true, description = 'An explosive charge that can be remotely detonated' },
    weapon_flare                 = { label = 'Flare pistol', weight = 1000, type = 'weapon', ammotype = 'AMMO_FLARE', unique = true, description = 'A small pyrotechnic devices used for illumination and signalling' },

    -- Miscellaneous
    weapon_petrolcan             = { label = 'Petrol Can', weight = 1000, type = 'weapon', ammotype = 'AMMO_PETROLCAN', unique = true, description = 'A robust liquid container made from pressed steel' },
    weapon_fireextinguisher      = { label = 'Fire Extinguisher', weight = 1000, type = 'weapon', unique = true, description = 'A portable device that discharges a jet of water, foam, gas, or other material to extinguish a fire' },
    weapon_hazardcan             = { label = 'Hazardous Jerry Can', weight = 1000, type = 'weapon', ammotype = 'AMMO_PETROLCAN', unique = true, useable = true, description = 'Weapon Hazardcan' },

    -- Weapon Attachments
    clip_attachment              = { label = 'Clip', weight = 1000, useable = true, shouldClose = true, description = 'A clip for a weapon' },
    drum_attachment              = { label = 'Drum', weight = 1000, useable = true, shouldClose = true, description = 'A drum for a weapon' },
    flashlight_attachment        = { label = 'Flashlight', weight = 1000, useable = true, shouldClose = true, description = 'A flashlight for a weapon' },
    suppressor_attachment        = { label = 'Suppressor', weight = 1000, useable = true, shouldClose = true, description = 'A suppressor for a weapon' },
    smallscope_attachment        = { label = 'Small Scope', weight = 1000, useable = true, shouldClose = true, description = 'A small scope for a weapon' },
    medscope_attachment          = { label = 'Medium Scope', weight = 1000, useable = true, shouldClose = true, description = 'A medium scope for a weapon' },
    largescope_attachment        = { label = 'Large Scope', weight = 1000, useable = true, shouldClose = true, description = 'A large scope for a weapon' },
    holoscope_attachment         = { label = 'Holo Scope', weight = 1000, useable = true, shouldClose = true, description = 'A holo scope for a weapon' },
    advscope_attachment          = { label = 'Advanced Scope', weight = 1000, useable = true, shouldClose = true, description = 'An advanced scope for a weapon' },
    nvscope_attachment           = { label = 'Night Vision Scope', weight = 1000, useable = true, shouldClose = true, description = 'A night vision scope for a weapon' },
    thermalscope_attachment      = { label = 'Thermal Scope', weight = 1000, useable = true, shouldClose = true, description = 'A thermal scope for a weapon' },
    flat_muzzle_brake            = { label = 'Flat Muzzle Brake', weight = 1000, useable = true, shouldClose = true, description = 'A muzzle brake for a weapon' },
    tactical_muzzle_brake        = { label = 'Tactical Muzzle Brake', weight = 1000, useable = true, shouldClose = true, description = 'A muzzle brakee for a weapon' },
    fat_end_muzzle_brake         = { label = 'Fat End Muzzle Brake', weight = 1000, useable = true, shouldClose = true, description = 'A muzzle brake for a weapon' },
    precision_muzzle_brake       = { label = 'Precision Muzzle Brake', weight = 1000, useable = true, shouldClose = true, description = 'A muzzle brake for a weapon' },
    heavy_duty_muzzle_brake      = { label = 'HD Muzzle Brake', weight = 1000, useable = true, shouldClose = true, description = 'A muzzle brake for a weapon' },
    slanted_muzzle_brake         = { label = 'Slanted Muzzle Brake', weight = 1000, useable = true, shouldClose = true, description = 'A muzzle brake for a weapon' },
    split_end_muzzle_brake       = { label = 'Split End Muzzle Brake', weight = 1000, useable = true, shouldClose = true, description = 'A muzzle brake for a weapon' },
    squared_muzzle_brake         = { label = 'Squared Muzzle Brake', weight = 1000, useable = true, shouldClose = true, description = 'A muzzle brake for a weapon' },
    bellend_muzzle_brake         = { label = 'Bellend Muzzle Brake', weight = 1000, useable = true, shouldClose = true, description = 'A muzzle brake for a weapon' },
    barrel_attachment            = { label = 'Barrel', weight = 1000, useable = true, shouldClose = true, description = 'A barrel for a weapon' },
    grip_attachment              = { label = 'Grip', weight = 1000, useable = true, shouldClose = true, description = 'A grip for a weapon' },
    comp_attachment              = { label = 'Compensator', weight = 1000, useable = true, shouldClose = true, description = 'A compensator for a weapon' },
    luxuryfinish_attachment      = { label = 'Luxury Finish', weight = 1000, useable = true, shouldClose = true, description = 'A luxury finish for a weapon' },
    digicamo_attachment          = { label = 'Digital Camo', weight = 1000, useable = true, shouldClose = true, description = 'A digital camo for a weapon' },
    brushcamo_attachment         = { label = 'Brushstroke Camo', weight = 1000, useable = true, shouldClose = true, description = 'A brushstroke camo for a weapon' },
    woodcamo_attachment          = { label = 'Woodland Camo', weight = 1000, useable = true, shouldClose = true, description = 'A woodland camo for a weapon' },
    skullcamo_attachment         = { label = 'Skull Camo', weight = 1000, useable = true, shouldClose = true, description = 'A skull camo for a weapon' },
    sessantacamo_attachment      = { label = 'Sessanta Nove Camo', weight = 1000, useable = true, shouldClose = true, description = 'A sessanta nove camo for a weapon' },
    perseuscamo_attachment       = { label = 'Perseus Camo', weight = 1000, useable = true, shouldClose = true, description = 'A perseus camo for a weapon' },
    leopardcamo_attachment       = { label = 'Leopard Camo', weight = 1000, useable = true, shouldClose = true, description = 'A leopard camo for a weapon' },
    zebracamo_attachment         = { label = 'Zebra Camo', weight = 1000, useable = true, shouldClose = true, description = 'A zebra camo for a weapon' },
    geocamo_attachment           = { label = 'Geometric Camo', weight = 1000, useable = true, shouldClose = true, description = 'A geometric camo for a weapon' },
    boomcamo_attachment          = { label = 'Boom Camo', weight = 1000, useable = true, shouldClose = true, description = 'A boom camo for a weapon' },
    patriotcamo_attachment       = { label = 'Patriot Camo', weight = 1000, useable = true, shouldClose = true, description = 'A patriot camo for a weapon' },

    -- Weapon Tints
    weapontint_0                 = { label = 'Default Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Default/Black Weapon Tint' },
    weapontint_1                 = { label = 'Green Tint', weight = 1000, image = 'weapontint_green.png', useable = true, shouldClose = true, description = 'Green Weapon Tint' },
    weapontint_2                 = { label = 'Gold Tint', weight = 1000, image = 'weapontint_gold.png', useable = true, shouldClose = true, description = 'Gold Weapon Tint' },
    weapontint_3                 = { label = 'Pink Tint', weight = 1000, image = 'weapontint_pink.png', useable = true, shouldClose = true, description = 'Pink Weapon Tint' },
    weapontint_4                 = { label = 'Army Tint', weight = 1000, image = 'weapontint_army.png', useable = true, shouldClose = true, description = 'Army Weapon Tint' },
    weapontint_5                 = { label = 'LSPD Tint', weight = 1000, image = 'weapontint_lspd.png', useable = true, shouldClose = true, description = 'LSPD Weapon Tint' },
    weapontint_6                 = { label = 'Orange Tint', weight = 1000, image = 'weapontint_orange.png', useable = true, shouldClose = true, description = 'Orange Weapon Tint' },
    weapontint_7                 = { label = 'Platinum Tint', weight = 1000, image = 'weapontint_plat.png', useable = true, shouldClose = true, description = 'Platinum Weapon Tint' },
    weapontint_mk2_0             = { label = 'Classic Black Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Classic Black Weapon Tint for MK2 Weapons' },
    weapontint_mk2_1             = { label = 'Classic Gray Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Classic Gray Weapon Tint for MK2 Weapons' },
    weapontint_mk2_2             = { label = 'Classic Two-Tone Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Classic Two-Tone Weapon Tint for MK2 Weapons' },
    weapontint_mk2_3             = { label = 'Classic White Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Classic White Weapon Tint for MK2 Weapons' },
    weapontint_mk2_4             = { label = 'Classic Beige Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Classic Beige Weapon Tint for MK2 Weapons' },
    weapontint_mk2_5             = { label = 'Classic Green Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Classic Green Weapon Tint for MK2 Weapons' },
    weapontint_mk2_6             = { label = 'Classic Blue Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Classic Blue Weapon Tint for MK2 Weapons' },
    weapontint_mk2_7             = { label = 'Classic Earth Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Classic Earth Weapon Tint for MK2 Weapons' },
    weapontint_mk2_8             = { label = 'Classic Brown & Black Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Classic Brown & Black Weapon Tint for MK2 Weapons' },
    weapontint_mk2_9             = { label = 'Red Contrast Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Red Contrast Weapon Tint for MK2 Weapons' },
    weapontint_mk2_10            = { label = 'Blue Contrast Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Blue Contrast Weapon Tint for MK2 Weapons' },
    weapontint_mk2_11            = { label = 'Yellow Contrast Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Yellow Contrast Weapon Tint for MK2 Weapons' },
    weapontint_mk2_12            = { label = 'Orange Contrast Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Orange Contrast Weapon Tint for MK2 Weapons' },
    weapontint_mk2_13            = { label = 'Bold Pink Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Bold Pink Weapon Tint for MK2 Weapons' },
    weapontint_mk2_14            = { label = 'Bold Purple & Yellow Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Bold Purple & Yellow Weapon Tint for MK2 Weapons' },
    weapontint_mk2_15            = { label = 'Bold Orange Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Bold Orange Weapon Tint for MK2 Weapons' },
    weapontint_mk2_16            = { label = 'Bold Green & Purple Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Bold Green & Purple Weapon Tint for MK2 Weapons' },
    weapontint_mk2_17            = { label = 'Bold Red Features Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Bold Red Features Weapon Tint for MK2 Weapons' },
    weapontint_mk2_18            = { label = 'Bold Green Features Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Bold Green Features Weapon Tint for MK2 Weapons' },
    weapontint_mk2_19            = { label = 'Bold Cyan Features Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Bold Cyan Features Weapon Tint for MK2 Weapons' },
    weapontint_mk2_20            = { label = 'Bold Yellow Features Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Bold Yellow Features Weapon Tint for MK2 Weapons' },
    weapontint_mk2_21            = { label = 'Bold Red & White Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Bold Red & White Weapon Tint for MK2 Weapons' },
    weapontint_mk2_22            = { label = 'Bold Blue & White Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Bold Blue & White Weapon Tint for MK2 Weapons' },
    weapontint_mk2_23            = { label = 'Metallic Gold Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Metallic Gold Weapon Tint for MK2 Weapons' },
    weapontint_mk2_24            = { label = 'Metallic Platinum Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Metallic Platinum Weapon Tint for MK2 Weapons' },
    weapontint_mk2_25            = { label = 'Metallic Gray & Lilac Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Metallic Gray & Lilac Weapon Tint for MK2 Weapons' },
    weapontint_mk2_26            = { label = 'Metallic Purple & Lime Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Metallic Purple & Lime Weapon Tint for MK2 Weapons' },
    weapontint_mk2_27            = { label = 'Metallic Red Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Metallic Red Weapon Tint for MK2 Weapons' },
    weapontint_mk2_28            = { label = 'Metallic Green Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Metallic Green Weapon Tint for MK2 Weapons' },
    weapontint_mk2_29            = { label = 'Metallic Blue Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Metallic Blue Weapon Tint for MK2 Weapons' },
    weapontint_mk2_30            = { label = 'Metallic White & Aqua Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Metallic White & Aqua Weapon Tint for MK2 Weapons' },
    weapontint_mk2_31            = { label = 'Metallic Orange & Yellow Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Metallic Orange & Yellow Weapon Tint for MK2 Weapons' },
    weapontint_mk2_32            = { label = 'Metallic Red and Yellow Tint', weight = 1000, image = 'weapontint_black.png', useable = true, shouldClose = true, description = 'Metallic Red and Yellow Weapon Tint for MK2 Weapons' },
    -- ITEMS

    -- Ammo ITEMS
    pistol_ammo                  = { label = 'Pistol ammo', weight = 200, useable = true, shouldClose = true, description = 'Ammo for Pistols' },
    rifle_ammo                   = { label = 'Rifle ammo', weight = 1000, useable = true, shouldClose = true, description = 'Ammo for Rifles' },
    smg_ammo                     = { label = 'SMG ammo', weight = 500, useable = true, shouldClose = true, description = 'Ammo for Sub Machine Guns' },
    shotgun_ammo                 = { label = 'Shotgun ammo', weight = 500, useable = true, shouldClose = true, description = 'Ammo for Shotguns' },
    mg_ammo                      = { label = 'MG ammo', weight = 1000, useable = true, shouldClose = true, description = 'Ammo for Machine Guns' },
    snp_ammo                     = { label = 'Sniper ammo', weight = 1000, image = 'rifle_ammo.png', useable = true, shouldClose = true, description = 'Ammo for Sniper Rifles' },
    emp_ammo                     = { label = 'EMP Ammo', weight = 200, useable = true, shouldClose = true, description = 'Ammo for EMP Launcher' },

    -- Card ITEMS
    id_card                      = { label = 'ID Card', unique = true, useable = true, description = 'A card containing all your information to identify yourself' },
    driver_license               = { label = 'Drivers License', unique = true, useable = true, description = 'Permit to show you can drive a vehicle' },
    lawyerpass                   = { label = 'Lawyer Pass', unique = true, useable = true, description = 'Pass exclusive to lawyers to show they can represent a suspect' },
    weaponlicense                = { label = 'Weapon License', image = 'weapon_license.png', unique = true, useable = true, shouldClose = true, description = 'Weapon License' },
    bank_card                    = { label = 'Bank Card', unique = true, useable = true, shouldClose = true, description = 'Used to access ATM' },
    security_card_01             = { label = 'Security Card A', useable = true, shouldClose = true, description = 'A security card... I wonder what it goes to' },
    security_card_02             = { label = 'Security Card B', useable = true, shouldClose = true, description = 'A security card... I wonder what it goes to' },

    -- Eat ITEMS
    tosti                        = { label = 'Grilled Cheese Sandwich', weight = 200, useable = true, shouldClose = true, description = 'Nice to eat' },
    twerks_candy                 = { label = 'Twerks', weight = 100, useable = true, shouldClose = true, description = 'Some delicious candy :O' },
    snikkel_candy                = { label = 'Snikkel', weight = 100, useable = true, shouldClose = true, description = 'Some delicious candy :O' },
    sandwich                     = { label = 'Sandwich', weight = 200, useable = true, shouldClose = true, description = 'Nice bread for your stomach' },

    -- Drink ITEMS
    water_bottle                 = { label = 'Bottle of Water', weight = 500, useable = true, shouldClose = true, description = 'For all the thirsty out there' },
    coffee                       = { label = 'Coffee', weight = 200, useable = true, shouldClose = true, description = 'Pump 4 Caffeine' },
    kurkakola                    = { label = 'Cola', weight = 500, image = 'cola.png', useable = true, shouldClose = true, description = 'For all the thirsty out there' },

    -- Alcohol
    beer                         = { label = 'Beer', weight = 500, useable = true, shouldClose = true, description = 'Nothing like a good cold beer!' },
    whiskey                      = { label = 'Whiskey', weight = 500, useable = true, shouldClose = true, description = 'For all the thirsty out there' },
    vodka                        = { label = 'Vodka', weight = 500, useable = true, shouldClose = true, description = 'For all the thirsty out there' },
    grape                        = { label = 'Grape', weight = 100, useable = true, description = 'Mmmmh yummie, grapes' },
    wine                         = { label = 'Wine', weight = 300, useable = true, description = 'Some good wine to drink on a fine evening' },
    grapejuice                   = { label = 'Grape Juice', weight = 200, useable = true, description = 'Grape juice is said to be healthy' },

    -- Drugs
    joint                        = { label = 'Joint', useable = true, shouldClose = true, description = 'Sidney would be very proud at you' },
    cokebaggy                    = { label = 'Bag of Coke', image = 'cocaine_baggy.png', useable = true, shouldClose = true, description = 'To get happy real quick' },
    crack_baggy                  = { label = 'Bag of Crack', useable = true, shouldClose = true, description = 'To get happy faster' },
    xtcbaggy                     = { label = 'Bag of XTC', image = 'xtc_baggy.png', useable = true, shouldClose = true, description = 'Pop those pills baby' },
    coke_brick                   = { label = 'Coke Brick', weight = 1000, unique = true, shouldClose = true, description = 'Heavy package of cocaine, mostly used for deals and takes a lot of space' },
    weed_brick                   = { label = 'Weed Brick', weight = 1000, shouldClose = true, description = '1KG Weed Brick to sell to large customers.' },
    coke_small_brick             = { label = 'Coke Package', weight = 350, unique = true, shouldClose = true, description = 'Small package of cocaine, mostly used for deals and takes a lot of space' },
    oxy                          = { label = 'Prescription Oxy', useable = true, shouldClose = true, description = 'The Label Has Been Ripped Off' },
    meth                         = { label = 'Meth', weight = 100, image = 'meth_baggy.png', useable = true, shouldClose = true, description = 'A baggie of Meth' },
    rolling_paper                = { label = 'Rolling Paper', shouldClose = true, description = 'Paper made specifically for encasing and smoking tobacco or cannabis.' },

    -- Seed And Weed
    weed_whitewidow              = { label = 'White Widow 2g', weight = 200, image = 'weed_baggy.png', useable = true, description = 'A weed bag with 2g White Widow' },
    weed_skunk                   = { label = 'Skunk 2g', weight = 200, image = 'weed_baggy.png', useable = true, description = 'A weed bag with 2g Skunk' },
    weed_purplehaze              = { label = 'Purple Haze 2g', weight = 200, image = 'weed_baggy.png', useable = true, description = 'A weed bag with 2g Purple Haze' },
    weed_ogkush                  = { label = 'OGKush 2g', weight = 200, image = 'weed_baggy.png', useable = true, description = 'A weed bag with 2g OG Kush' },
    weed_amnesia                 = { label = 'Amnesia 2g', weight = 200, image = 'weed_baggy.png', useable = true, description = 'A weed bag with 2g Amnesia' },
    weed_ak47                    = { label = 'AK47 2g', weight = 200, image = 'weed_baggy.png', useable = true, description = 'A weed bag with 2g AK47' },
    weed_whitewidow_seed         = { label = 'White Widow Seed', image = 'weed_seed.png', useable = true, description = 'A weed seed of White Widow' },
    weed_skunk_seed              = { label = 'Skunk Seed', image = 'weed_seed.png', useable = true, shouldClose = true, description = 'A weed seed of Skunk' },
    weed_purplehaze_seed         = { label = 'Purple Haze Seed', image = 'weed_seed.png', useable = true, shouldClose = true, description = 'A weed seed of Purple Haze' },
    weed_ogkush_seed             = { label = 'OGKush Seed', image = 'weed_seed.png', useable = true, shouldClose = true, description = 'A weed seed of OG Kush' },
    weed_amnesia_seed            = { label = 'Amnesia Seed', image = 'weed_seed.png', useable = true, shouldClose = true, description = 'A weed seed of Amnesia' },
    weed_ak47_seed               = { label = 'AK47 Seed', image = 'weed_seed.png', useable = true, shouldClose = true, description = 'A weed seed of AK47' },
    empty_weed_bag               = { label = 'Empty Weed Bag', image = 'weed_baggy_empty.png', useable = true, shouldClose = true, description = 'A small empty bag' },
    weed_nutrition               = { label = 'Plant Fertilizer', weight = 2000, useable = true, shouldClose = true, description = 'Plant nutrition' },

    -- Material
    plastic                      = { label = 'Plastic', weight = 100, description = 'RECYCLE! - Greta Thunberg 2019' },
    metalscrap                   = { label = 'Metal Scrap', weight = 100, description = 'You can probably make something nice out of this' },
    copper                       = { label = 'Copper', weight = 100, description = 'Nice piece of metal that you can probably use for something' },
    aluminum                     = { label = 'Aluminium', weight = 100, description = 'Nice piece of metal that you can probably use for something' },
    aluminumoxide                = { label = 'Aluminium Powder', weight = 100, description = 'Some powder to mix with' },
    iron                         = { label = 'Iron', weight = 100, description = 'Handy piece of metal that you can probably use for something' },
    ironoxide                    = { label = 'Iron Powder', weight = 100, description = 'Some powder to mix with.' },
    steel                        = { label = 'Steel', weight = 100, description = 'Nice piece of metal that you can probably use for something' },
    rubber                       = { label = 'Rubber', weight = 100, description = 'Rubber, I believe you can make your own rubber ducky with it :D' },
    glass                        = { label = 'Glass', weight = 100, description = 'It is very fragile, watch out' },

    -- Tools
    lockpick                     = { label = 'Lockpick', weight = 300, useable = true, shouldClose = true, description = 'Very useful if you lose your keys a lot.. or if you want to use it for something else...' },
    advancedlockpick             = { label = 'Advanced Lockpick', weight = 500, useable = true, shouldClose = true, description = 'If you lose your keys a lot this is very useful... Also useful to open your beers' },
    electronickit                = { label = 'Electronic Kit', weight = 100, useable = true, shouldClose = true, description = 'If you\'ve always wanted to build a robot you can maybe start here. Maybe you\'ll be the new Elon Musk?' },
    gatecrack                    = { label = 'Gatecrack', image = 'usb_device.png', shouldClose = true, description = 'Handy software to tear down some fences' },
    thermite                     = { label = 'Thermite', weight = 1000, useable = true, shouldClose = true, description = 'Sometimes you\'d wish for everything to burn' },
    trojan_usb                   = { label = 'Trojan USB', image = 'usb_device.png', shouldClose = true, description = 'Handy software to shut down some systems' },
    screwdriverset               = { label = 'Toolkit', weight = 1000, description = 'Very useful to screw... screws...' },
    drill                        = { label = 'Drill', weight = 20000, description = 'The real deal...' },

    -- Vehicle Tools
    nitrous                      = { label = 'Nitrous', weight = 1000, useable = true, shouldClose = true, description = 'Speed up, gas pedal! :D' },
    repairkit                    = { label = 'Repairkit', weight = 2500, useable = true, shouldClose = true, description = 'A nice toolbox with stuff to repair your vehicle' },
    advancedrepairkit            = { label = 'Advanced Repairkit', weight = 4000, image = 'advancedkit.png', useable = true, shouldClose = true, description = 'A nice toolbox with stuff to repair your vehicle' },
    cleaningkit                  = { label = 'Cleaning Kit', weight = 250, useable = true, shouldClose = true, description = 'A microfiber cloth with some soap will let your car sparkle again!' },
    tunerlaptop                  = { label = 'Tunerchip', weight = 2000, image = 'tunerchip.png', unique = true, useable = true, shouldClose = true, description = 'With this tunerchip you can get your car on steroids... If you know what you\'re doing' },
    harness                      = { label = 'Race Harness', weight = 1000, unique = true, useable = true, shouldClose = true, description = 'Racing Harness so no matter what you stay in the car' },
    jerry_can                    = { label = 'Jerrycan 20L', weight = 20000, useable = true, shouldClose = true, description = 'A can full of Fuel' },
    tirerepairkit                = { label = 'Tire Repair Kit', weight = 1000, useable = true, shouldClose = true, description = 'A kit to repair your tires' },

    -- Mechanic Parts
    veh_toolbox                  = { label = 'Toolbox', weight = 1000, useable = true, shouldClose = true, description = 'Check vehicle status' },
    veh_armor                    = { label = 'Armor', weight = 1000, useable = true, shouldClose = true, description = 'Upgrade vehicle armor' },
    veh_brakes                   = { label = 'Brakes', weight = 1000, useable = true, shouldClose = true, description = 'Upgrade vehicle brakes' },
    veh_engine                   = { label = 'Engine', weight = 1000, useable = true, shouldClose = true, description = 'Upgrade vehicle engine' },
    veh_suspension               = { label = 'Suspension', weight = 1000, useable = true, shouldClose = true, description = 'Upgrade vehicle suspension' },
    veh_transmission             = { label = 'Transmission', weight = 1000, useable = true, shouldClose = true, description = 'Upgrade vehicle transmission' },
    veh_turbo                    = { label = 'Turbo', weight = 1000, useable = true, shouldClose = true, description = 'Install vehicle turbo' },
    veh_interior                 = { label = 'Interior', weight = 1000, useable = true, shouldClose = true, description = 'Upgrade vehicle interior' },
    veh_exterior                 = { label = 'Exterior', weight = 1000, useable = true, shouldClose = true, description = 'Upgrade vehicle exterior' },
    veh_wheels                   = { label = 'Wheels', weight = 1000, useable = true, shouldClose = true, description = 'Upgrade vehicle wheels' },
    veh_neons                    = { label = 'Neons', weight = 1000, useable = true, shouldClose = true, description = 'Upgrade vehicle neons' },
    veh_xenons                   = { label = 'Xenons', weight = 1000, useable = true, shouldClose = true, description = 'Upgrade vehicle xenons' },
    veh_tint                     = { label = 'Tints', weight = 1000, useable = true, shouldClose = true, description = 'Install vehicle tint' },
    veh_plates                   = { label = 'Plates', weight = 1000, useable = true, shouldClose = true, description = 'Install vehicle plates' },

    -- Medication
    firstaid                     = { label = 'First Aid', weight = 2500, useable = true, shouldClose = true, description = 'You can use this First Aid kit to get people back on their feet' },
    bandage                      = { label = 'Bandage', useable = true, shouldClose = true, description = 'A bandage works every time' },
    ifaks                        = { label = 'ifaks', weight = 200, useable = true, shouldClose = true, description = 'ifaks for healing and a complete stress remover.' },
    painkillers                  = { label = 'Painkillers', useable = true, shouldClose = true, description = 'For pain you can\'t stand anymore, take this pill that\'d make you feel great again' },
    walkstick                    = { label = 'Walking Stick', weight = 1000, useable = true, shouldClose = true, description = 'Walking stick for ya\'ll grannies out there.. HAHA' },

    -- Communication
    phone                        = { label = 'Phone', weight = 700, unique = true, description = 'Neat phone ya got there' },
    radio                        = { label = 'Radio', weight = 2000, unique = true, useable = true, shouldClose = true, description = 'You can communicate with this through a signal' },
    iphone                       = { label = 'iPhone', weight = 1000, shouldClose = true, description = 'Very expensive phone' },
    samsungphone                 = { label = 'Samsung S10', weight = 1000, shouldClose = true, description = 'Very expensive phone' },
    laptop                       = { label = 'Laptop', weight = 4000, shouldClose = true, description = 'Expensive laptop' },
    tablet                       = { label = 'Tablet', weight = 2000, shouldClose = true, description = 'Expensive tablet' },
    fitbit                       = { label = 'Fitbit', weight = 500, unique = true, useable = true, shouldClose = true, description = 'I like fitbit' },
    radioscanner                 = { label = 'Radio Scanner', weight = 1000, shouldClose = true, description = 'With this you can get some police alerts. Not 100% effective however' },
    pinger                       = { label = 'Pinger', weight = 1000, shouldClose = true, description = 'With a pinger and your phone you can send out your location' },
    cryptostick                  = { label = 'Crypto Stick', weight = 200, unique = true, useable = true, shouldClose = true, description = 'Why would someone ever buy money that doesn\'t exist.. How many would it contain..?' },

    -- Theft and Jewelry
    rolex                        = { label = 'Golden Watch', weight = 1500, shouldClose = true, description = 'A golden watch seems like the jackpot to me!' },
    diamond_ring                 = { label = 'Diamond Ring', weight = 1500, shouldClose = true, description = 'A diamond ring seems like the jackpot to me!' },
    diamond                      = { label = 'Diamond', weight = 1000, shouldClose = true, description = 'A diamond seems like the jackpot to me!' },
    goldchain                    = { label = 'Golden Chain', weight = 1500, shouldClose = true, description = 'A golden chain seems like the jackpot to me!' },
    tenkgoldchain                = { label = '10k Gold Chain', weight = 2000, image = '10kgoldchain.png', shouldClose = true, description = '10 carat golden chain' },
    goldbar                      = { label = 'Gold Bar', weight = 7000, shouldClose = true, description = 'Looks pretty expensive to me' },

    -- Cops Tools
    armor                        = { label = 'Armor', weight = 5000, useable = true, shouldClose = true, description = 'Some protection won\'t hurt... right?' },
    heavyarmor                   = { label = 'Heavy Armor', weight = 5000, useable = true, shouldClose = true, description = 'Some protection won\'t hurt... right?' },
    handcuffs                    = { label = 'Handcuffs', weight = 100, useable = true, shouldClose = true, description = 'Comes in handy when people misbehave. Maybe it can be used for something else?' },
    police_stormram              = { label = 'Stormram', weight = 18000, useable = true, shouldClose = true, description = 'A nice tool to break into doors' },
    empty_evidence_bag           = { label = 'Empty Evidence Bag', image = 'evidence.png', description = 'Used a lot to keep DNA from blood, bullet shells and more' },
    filled_evidence_bag          = { label = 'Evidence Bag', weight = 200, image = 'evidence.png', unique = true, description = 'A filled evidence bag to see who committed the crime >:(' },

    -- Firework Tools
    firework1                    = { label = '2Brothers', weight = 1000, useable = true, shouldClose = true, description = 'Fireworks' },
    firework2                    = { label = 'Poppelers', weight = 1000, useable = true, shouldClose = true, description = 'Fireworks' },
    firework3                    = { label = 'WipeOut', weight = 1000, useable = true, shouldClose = true, description = 'Fireworks' },
    firework4                    = { label = 'Weeping Willow', weight = 1000, useable = true, shouldClose = true, description = 'Fireworks' },

    -- Sea Tools
    dendrogyra_coral             = { label = 'Dendrogyra', weight = 1000, shouldClose = true, description = 'Its also known as pillar coral' },
    antipatharia_coral           = { label = 'Antipatharia', weight = 1000, shouldClose = true, description = 'Its also known as black corals or thorn corals' },
    diving_gear                  = { label = 'Diving Gear', weight = 30000, unique = true, useable = true, shouldClose = true, description = 'An oxygen tank and a rebreather' },
    diving_fill                  = { label = 'Diving Tube', weight = 3000, image = 'diving_tube.png', unique = true, useable = true, shouldClose = true, description = 'An oxygen tube and a rebreather' },

    -- Other Tools
    casinochips                  = { label = 'Casino Chips', description = 'Chips For Casino Gambling' },
    stickynote                   = { label = 'Sticky note', unique = true, description = 'Sometimes handy to remember something :)' },
    moneybag                     = { label = 'Money Bag', unique = true, useable = true, shouldClose = true, description = 'A bag with cash' },
    parachute                    = { label = 'Parachute', weight = 30000, unique = true, useable = true, shouldClose = true, description = 'The sky is the limit! Woohoo!' },
    binoculars                   = { label = 'Binoculars', weight = 600, useable = true, shouldClose = true, description = 'Sneaky Breaky...' },
    lighter                      = { label = 'Lighter', shouldClose = true, description = 'On new years eve a nice fire to stand next to' },
    certificate                  = { label = 'Certificate', shouldClose = true, description = 'Certificate that proves you own certain stuff' },
    markedbills                  = { label = 'Marked Money', weight = 1000, unique = true, shouldClose = true, description = 'Money?' },
    labkey                       = { label = 'Key', weight = 500, unique = true, useable = true, shouldClose = true, description = 'Key for a lock...?' },
    printerdocument              = { label = 'Document', weight = 500, unique = true, useable = true, shouldClose = true, description = 'A nice document' },
    newscam                      = { label = 'News Camera', weight = 100, unique = true, useable = true, shouldClose = true, description = 'A camera for the news' },
    newsmic                      = { label = 'News Microphone', weight = 100, unique = true, useable = true, shouldClose = true, description = 'A microphone for the news' },
    newsbmic                     = { label = 'Boom Microphone', weight = 100, unique = true, useable = true, shouldClose = true, description = 'A Useable BoomMic' },
}

QBShared.Items = {}

for key, values in pairs(Items) do
    QBShared.Items[key] = {
        name = values.name or key,
        label = values.label or key,
        weight = values.weight or 0,
        type = values.type or 'item',
        image = values.image or ("%s.png"):format(key),
        unique = values.unique or false,
        useable = values.useable or false,
        shouldClose = values.shouldClose or false,
        description = values.description or '',
    }
end