QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civilian', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 10 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 50 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 50 } } },
	vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 50 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 50 } } },
	---------------------
	-- City Government --
	---------------------
	cityhall = {
		label = 'LS Municipality Services',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'City Employee', payment = 100 },
			['1'] = {name = 'Administrative Staff', payment = 125 },
			['2'] = {name = 'City Manager', payment = 150 },
			['3'] = {name = 'Deputy Mayor', payment = 175 },
			['4'] = {name = 'Mayor', isboss = true, payment = 200 },
		},
	},
	----------------------------
	-- Justice & Criminal Law --
	----------------------------
	judge = {
		label = 'San Andreas Criminal Court',
		type = 'doj',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Bailiff', payment = 100 },
			['1'] = {name = 'Court Staff', payment = 125 },
			['2'] = {name = 'Magistrate', payment = 150 },
			['3'] = {name = 'Judge', payment = 175 },
			['4'] = {name = 'Associate Judge', payment = 200 },
			['5'] = {name = 'Senior Judge', payment = 225 },
			['6'] = {name = 'Chief Justice', isboss = true, payment = 250 },
		},
	},
	lawyer = {
		label = 'Feist & Welch LLP',
		type = 'doj',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Intern', payment = 100 },
			['1'] = {name = 'Lawyer', payment = 125 },
			['2'] = {name = 'Associate', payment = 150 },
			['3'] = {name = 'Senior Associate', payment = 175 },
			['4'] = {name = 'Special Council', payment = 200 },
			['5'] = {name = 'Managing Partner', payment = 225 },
			['6'] = {name = 'Law Firm CEO', isboss = true, payment = 250 },
		},
	},
	---------------------------------
	-- Law Enforcement Departments --
	---------------------------------
	police = {
		label = 'Law Enforcement',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = { name = 'Police Recruit', payment = 100 },
			['1'] = { name = 'Police Officer I', payment = 125 },
			['2'] = { name = 'Police Officer II', payment = 150 },
			['3'] = { name = 'Police Officer III', payment = 175 },
			['4'] = { name = 'Police Officer IV', payment = 200 },
			['5'] = { name = 'Sergeant I', payment = 225 },
			['6'] = { name = 'Sergeant II', payment = 250 },
			['7'] = { name = 'Detective I', payment = 275 },
			['8'] = { name = 'Detective II', payment = 300 },
			['9'] = { name = 'Detective III', payment = 325 },
			['10'] = { name = 'Lieutenant I', payment = 350 },
			['11'] = { name = 'Lieutenant II', payment = 375 },
			['12'] = { name = 'Captain I', payment = 400 },
			['13'] = { name = 'Captain II', payment = 425 },
			['14'] = { name = 'Captain III', payment = 450 },
			['15'] = { name = 'Commander', payment = 475 },
			['16'] = { name = 'Deputy Chief', payment = 500 },
			['17'] = { name = 'Assistant Chief', payment = 525 },
			['18'] = { name = 'Chief of Police', isboss = true, payment = 550 },
		},
	},
	lssd = {
		label = 'Los Santos Sheriffs Department',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        	['0'] = {name = 'Deputy Sheriff Trainee', payment = 100 },
			['1'] = {name = 'Deputy Sheriff', payment = 125 },
			['2'] = {name = 'Deputy Sheriff I', payment = 150 },
			['3'] = {name = 'Deputy Sheriff II', payment = 175 },
			['4'] = {name = 'Deputy Sheriff III', payment = 200 },
			['5'] = {name = 'Sergeant', payment = 225 },
			['6'] = {name = 'Lieutenant', payment = 250 },
			['7'] = {name = 'Captain', payment = 275 },
			['8'] = {name = 'Area Commander', payment = 300 },
			['9'] = {name = 'Division Chief', payment = 325 },
			['10'] = {name = 'Assistant Sheriff', payment = 350 },
			['11'] = {name = 'Undersheriff', payment = 375 },
			['12'] = {name = 'Sheriff', isboss = true, payment = 400 },
		},
	},
	bcso = {
		label = 'Blaine County Sheriffs Office',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Deputy Sheriff Trainee', payment = 100 },
			['1'] = {name = 'Deputy Sheriff', payment = 125 },
			['2'] = {name = 'Deputy Sheriff I', payment = 150 },
			['3'] = {name = 'Deputy Sheriff II', payment = 175 },
			['4'] = {name = 'Deputy Sheriff III', payment = 200 },
			['5'] = {name = 'Sergeant', payment = 225 },
			['6'] = {name = 'Lieutenant', payment = 250 },
			['7'] = {name = 'Captain', payment = 275 },
			['8'] = {name = 'Area Commander', payment = 300 },
			['9'] = {name = 'Division Chief', payment = 325 },
			['10'] = {name = 'Assistant Sheriff', payment = 350 },
			['11'] = {name = 'Undersheriff', payment = 375 },
			['12'] = {name = 'Sheriff', isboss = true, payment = 400 },
		},
	},
	sahp = {
		label = 'San Andreas Highway Patrol',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Cadet', payment = 100 },
			['1'] = {name = 'Officer', payment = 125 },
			['2'] = {name = 'Sergeant', payment = 150 },
			['3'] = {name = 'Lieutenant', payment = 175 },
			['4'] = {name = 'Captain', payment = 200 },
			['5'] = {name = 'Assistant Chief', payment = 225 },
			['6'] = {name = 'Chief', payment = 250 },
			['7'] = {name = 'Asst. Commissioner', payment = 275 },
			['8'] = {name = 'Deputy Commissioner', payment = 300 },
			['9'] = {name = 'Commissioner', isboss = true, payment = 325 },
		},
	},
	doc = {
		label = 'San Andreas Dept. of Corrections',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Corrections Trainee', payment = 100 },
			['1'] = {name = 'Corrections Officer', payment = 125 },
			['2'] = {name = 'Sr. Corrections Officer', payment = 150 },
			['3'] = {name = 'Corrections Corporal', payment = 175 },
			['4'] = {name = 'Corrections Sergeant', payment = 200 },
			['5'] = {name = 'Corrections Lieutenant', payment = 225 },
			['6'] = {name = 'Corrections Captain', payment = 250 },
			['7'] = {name = 'Deputy Warden', payment = 275 },
			['8'] = {name = 'Warden', payment = 300 },
			['9'] = {name = 'Commissioner', isboss = true, payment = 325 },
		},
	},
	sapr = {
		label = 'San Andreas Park Rangers',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Cadet', payment = 100 },
			['1'] = {name = 'Ranger', payment = 125 },
			['2'] = {name = 'Ranger 1st Class', payment = 150 },
			['3'] = {name = 'Senior Ranger', payment = 175 },
			['4'] = {name = 'Ranger Corporal', payment = 200 },
			['5'] = {name = 'Ranger Sergeant', payment = 225 },
			['6'] = {name = 'Ranger Lieutenant', payment = 250 },
			['7'] = {name = 'Ranger Captain', payment = 275 },
			['8'] = {name = 'Deputy Game Warden', payment = 300 },
			['9'] = {name = 'Game Warden', isboss = true, payment = 325 },
		},
	},
	fib = {
		label = 'Federal Investigations Bureau',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'New Agent Trainee', payment = 100 },
			['1'] = {name = 'Special Agent', payment = 125 },
			['2'] = {name = 'Senior Special Agent', payment = 150 },
			['3'] = {name = 'Supervisory Special Agent', payment = 175 },
			['4'] = {name = 'Assistant Special Agent In Charge', payment = 200 },
			['5'] = {name = 'Special Agent In Charge', payment = 225 },
			['6'] = {name = 'Deputy Assistant Director', payment = 250 },
			['7'] = {name = 'Assistant Director', payment = 275 },
			['8'] = {name = 'Associate Executive Assistant Director', payment = 300 },
			['9'] = {name = 'Executive Assistant Director', payment = 325 },
			['10'] = {name = 'Associate Deputy Director', payment = 350 },
			['11'] = {name = 'Deputy Chief Of Staff', payment = 375 },
			['12'] = {name = 'Chief Of Staff', payment = 400 },
			['13'] = {name = 'Deputy Director', payment = 425 },
			['14'] = {name = 'Director', isboss = true, payment = 450 },
		},
	},
	----------------------------
	-- Fire & Medical Service --
	----------------------------
	fire = {
		label = 'Los Santos Fire Department',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Firefighter EMT I', payment = 100 },
			['1'] = {name = 'Firefighter EMT II', payment = 125 },
			['2'] = {name = 'Firefighter EMT III', payment = 150 },
			['3'] = {name = 'Engineer', payment = 175 },
			['4'] = {name = 'Apparatus Operator', payment = 200 },
			['5'] = {name = 'Lieutenant', payment = 225 },
			['6'] = {name = 'Captain I', payment = 250 },
			['7'] = {name = 'Captain II', payment = 275 },
			['8'] = {name = 'Battalion Chief', payment = 300 },
			['9'] = {name = 'Assistant Chief', payment = 325 },
			['10'] = {name = 'Deputy Chief', payment = 350 },
			['11'] = {name = 'Chief Deputy', payment = 375 },
			['12'] = {name = 'Chief', isboss = true, payment = 400 },
		},
	},
	hospital = {
		label = 'Pillbox Medical Center',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Pre-Med Student', payment = 100 },
			['1'] = {name = 'Medical Student', payment = 125 },
			['2'] = {name = 'Intern', payment = 150 },
			['3'] = {name = 'Junior Resident', payment = 175 },
			['4'] = {name = 'Senior Resident', payment = 200 },
			['5'] = {name = 'Chief Resident', payment = 225 },
			['6'] = {name = 'Fellow', payment = 250 },
			['7'] = {name = 'Attending Physician', payment = 275 },
			['8'] = {name = 'Head of Department', payment = 300 },
			['9'] = {name = 'Medical Director', isboss = true, payment = 325 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Trainee', payment = 100 },
			['1'] = {name = 'Probationary EMT', payment = 125 },
			['2'] = {name = 'Emergency Medical Technician', payment = 150 },
			['3'] = {name = 'Advanced EMT', payment = 175 },
			['4'] = {name = 'EMS Paramedic', payment = 200 },
			['5'] = {name = 'EMS Lieutenant', payment = 225 },
			['6'] = {name = 'EMS Captain', payment = 250 },
			['7'] = {name = 'EMS Deputy Chief', payment = 275 },
			['8'] = {name = 'EMS Chief', isboss = true, payment = 300 },
		},
	},
	---------------------------------
	-- Home & Business Real Estate --
	---------------------------------
	dynasty8 = {
		label = 'Dynasty 8 Realty Co.',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Trainee', payment = 100 },
			['1'] = {name = 'Residential Agent', payment = 125 },
			['2'] = {name = 'Commercial Business', payment = 150 },
			['3'] = {name = 'Broker', payment = 175 },
			['4'] = {name = 'Assistant Manager', payment = 200 },
			['5'] = {name = 'General Manager', isboss = true, payment = 225 },
		},
	},
	realestate = {
		label = 'Real Estate',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'House Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Broker', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	---------------------
	-- Banking Careers --
	---------------------
	mazebank = {
		label = 'Maze Bank Financial Advisors',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Trainee', payment = 100 },
			['1'] = {name = 'Bank Teller', payment = 125 },
			['2'] = {name = 'Financial Advisor', payment = 150 },
			['3'] = {name = 'Assistant Manager', payment = 175 },
			['4'] = {name = 'Branch Manager', payment = 200 },
			['5'] = {name = 'Branch President', isboss = true, payment = 225 },
		},
	},
	banker = {
		label = 'Pacific National Bank',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {name = 'Trainee', payment = 100 },
			['1'] = {name = 'Bank Teller', payment = 125 },
			['2'] = {name = 'Financial Advisor', payment = 150 },
			['3'] = {name = 'Assistant Manager', payment = 175 },
			['4'] = {name = 'Branch Manager', payment = 200 },
			['5'] = {name = 'Branch President', isboss = true, payment = 225 },
		},
	},
	----------------------------------------
	-- Automotive Sales & Repair Services --
	----------------------------------------
	cardealer = { -- PDM In Downtown
		label = 'Premium Deluxe Motorsports',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 100 },
			['1'] = { name = 'Showroom Sales', payment = 125 },
			['2'] = { name = 'Business Sales', payment = 150 },
			['3'] = { name = 'Finance', payment = 175 },
			['4'] = { name = 'Manager', isboss = true, payment = 200 },
		},
	},
	luxuryautosales = {
		label = 'Luxury Autos',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 100 },
			['1'] = { name = 'Showroom Sales', payment = 125 },
			['2'] = { name = 'Business Sales', payment = 150 },
			['3'] = { name = 'Finance', payment = 175 },
			['4'] = { name = 'Manager', isboss = true, payment = 200 },
		},
	},
	---------------
	-- Mechanics --
	---------------
	bennys = { -- South of Downtown
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Shop Apprentice', payment = 100 },
			['1'] = {name = 'Service Tech I', payment = 125 },
			['2'] = {name = 'Service Tech II', payment = 150 },
			['3'] = {name = 'Service Advisor', payment = 175 },
			['4'] = {name = 'Manager', payment = 200 },
			['5'] = {name = 'Owner', isboss = true, payment = 225 },
		},
	},
	beeker = { -- Paleto Bay Truck Stop
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Shop Apprentice', payment = 100 },
			['1'] = {name = 'Service Tech I', payment = 125 },
			['2'] = {name = 'Service Tech II', payment = 150 },
			['3'] = {name = 'Service Advisor', payment = 175 },
			['4'] = {name = 'Manager', payment = 200 },
			['5'] = {name = 'Owner', isboss = true, payment = 225 },
		},
	},
	lscustoms = {
		label = 'LS Customs & Tuning',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
        		['0'] = {name = 'Shop Apprentice', payment = 100 },
			['1'] = {name = 'Service Tech I', payment = 125 },
			['2'] = {name = 'Service Tech II', payment = 150 },
			['3'] = {name = 'Service Advisor', payment = 175 },
			['4'] = {name = 'Manager', payment = 200 },
			['5'] = {name = 'Owner', isboss = true, payment = 225 },
		},
	},
	-- mechanic2 = {
	-- 	label = 'LS Customs & Tuning',
	-- 	type = 'mechanic',
	-- 	defaultDuty = true,
	-- 	offDutyPay = false,
	-- 	grades = {
 --        		['0'] = {name = 'Shop Apprentice', payment = 100 },
	-- 		['1'] = {name = 'Service Tech I', payment = 125 },
	-- 		['2'] = {name = 'Service Tech II', payment = 150 },
	-- 		['3'] = {name = 'Service Advisor', payment = 175 },
	-- 		['4'] = {name = 'Manager', payment = 200 },
	-- 		['5'] = {name = 'Owner', isboss = true, payment = 225 },
	-- 	},
	-- },
	-- mechanic3 = {
	-- 	label = 'LS Customs & Tuning',
	-- 	type = 'mechanic',
	-- 	defaultDuty = true,
	-- 	offDutyPay = false,
	-- 	grades = {
 --        		['0'] = {name = 'Shop Apprentice', payment = 100 },
	-- 		['1'] = {name = 'Service Tech I', payment = 125 },
	-- 		['2'] = {name = 'Service Tech II', payment = 150 },
	-- 		['3'] = {name = 'Service Advisor', payment = 175 },
	-- 		['4'] = {name = 'Manager', payment = 200 },
	-- 		['5'] = {name = 'Owner', isboss = true, payment = 225 },
	-- 	},
	-- },
	--------------------------
	-- Other Jobs & Careers --
	--------------------------
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 100 },
			['1'] = { name = 'Driver', payment = 125 },
			['2'] = { name = 'Event Driver', payment = 150 },
			['3'] = { name = 'Dispatcher', payment = 175 },
			['4'] = { name = 'Manager', isboss = true, payment = 200 },
		},
	},
	---------------------------------------------------------------------------------
	-- Add Your Other Custom Jobs Below In The Same Format & Modify To Your Liking --
	---------------------------------------------------------------------------------
	-- Example
	-- 
	-- jobname = { -- Will automatically generate a bank account if using qb banking by default
	-- 	label = 'Whats it called', -- Your business name
	-- 	defaultDuty = true,
	-- 	offDutyPay = false,
	-- 	grades = { -- Positions Below, Name The Titles To Your Liking
	-- 		['0'] = { name = 'Employee1', payment = 100 },
	-- 		['1'] = { name = 'Employee2', payment = 125 },
	-- 		['2'] = { name = 'Employee3', payment = 150 },
	-- 		['3'] = { name = 'Manager', payment = 175 },
	-- 		['4'] = { name = 'Owner', isboss = true, payment = 200 },
	-- 	},
	-- },
}
